//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceBox_3D.BrailleServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BrailleServiceReference.BrailleServiceSoap")]
    public interface BrailleServiceSoap {
        
        // CODEGEN: Generating message contract since element name input from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConvertTextToBraille", ReplyAction="*")]
        SpaceBox_3D.BrailleServiceReference.ConvertTextToBrailleResponse ConvertTextToBraille(SpaceBox_3D.BrailleServiceReference.ConvertTextToBrailleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConvertTextToBraille", ReplyAction="*")]
        System.Threading.Tasks.Task<SpaceBox_3D.BrailleServiceReference.ConvertTextToBrailleResponse> ConvertTextToBrailleAsync(SpaceBox_3D.BrailleServiceReference.ConvertTextToBrailleRequest request);
        
        // CODEGEN: Generating message contract since element name input from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDotsAmount", ReplyAction="*")]
        SpaceBox_3D.BrailleServiceReference.GetDotsAmountResponse GetDotsAmount(SpaceBox_3D.BrailleServiceReference.GetDotsAmountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDotsAmount", ReplyAction="*")]
        System.Threading.Tasks.Task<SpaceBox_3D.BrailleServiceReference.GetDotsAmountResponse> GetDotsAmountAsync(SpaceBox_3D.BrailleServiceReference.GetDotsAmountRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertTextToBrailleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertTextToBraille", Namespace="http://tempuri.org/", Order=0)]
        public SpaceBox_3D.BrailleServiceReference.ConvertTextToBrailleRequestBody Body;
        
        public ConvertTextToBrailleRequest() {
        }
        
        public ConvertTextToBrailleRequest(SpaceBox_3D.BrailleServiceReference.ConvertTextToBrailleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConvertTextToBrailleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public ConvertTextToBrailleRequestBody() {
        }
        
        public ConvertTextToBrailleRequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertTextToBrailleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertTextToBrailleResponse", Namespace="http://tempuri.org/", Order=0)]
        public SpaceBox_3D.BrailleServiceReference.ConvertTextToBrailleResponseBody Body;
        
        public ConvertTextToBrailleResponse() {
        }
        
        public ConvertTextToBrailleResponse(SpaceBox_3D.BrailleServiceReference.ConvertTextToBrailleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConvertTextToBrailleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConvertTextToBrailleResult;
        
        public ConvertTextToBrailleResponseBody() {
        }
        
        public ConvertTextToBrailleResponseBody(string ConvertTextToBrailleResult) {
            this.ConvertTextToBrailleResult = ConvertTextToBrailleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDotsAmountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDotsAmount", Namespace="http://tempuri.org/", Order=0)]
        public SpaceBox_3D.BrailleServiceReference.GetDotsAmountRequestBody Body;
        
        public GetDotsAmountRequest() {
        }
        
        public GetDotsAmountRequest(SpaceBox_3D.BrailleServiceReference.GetDotsAmountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDotsAmountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public GetDotsAmountRequestBody() {
        }
        
        public GetDotsAmountRequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDotsAmountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDotsAmountResponse", Namespace="http://tempuri.org/", Order=0)]
        public SpaceBox_3D.BrailleServiceReference.GetDotsAmountResponseBody Body;
        
        public GetDotsAmountResponse() {
        }
        
        public GetDotsAmountResponse(SpaceBox_3D.BrailleServiceReference.GetDotsAmountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDotsAmountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetDotsAmountResult;
        
        public GetDotsAmountResponseBody() {
        }
        
        public GetDotsAmountResponseBody(int GetDotsAmountResult) {
            this.GetDotsAmountResult = GetDotsAmountResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BrailleServiceSoapChannel : SpaceBox_3D.BrailleServiceReference.BrailleServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BrailleServiceSoapClient : System.ServiceModel.ClientBase<SpaceBox_3D.BrailleServiceReference.BrailleServiceSoap>, SpaceBox_3D.BrailleServiceReference.BrailleServiceSoap {
        
        public BrailleServiceSoapClient() {
        }
        
        public BrailleServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BrailleServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BrailleServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BrailleServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SpaceBox_3D.BrailleServiceReference.ConvertTextToBrailleResponse SpaceBox_3D.BrailleServiceReference.BrailleServiceSoap.ConvertTextToBraille(SpaceBox_3D.BrailleServiceReference.ConvertTextToBrailleRequest request) {
            return base.Channel.ConvertTextToBraille(request);
        }
        
        public string ConvertTextToBraille(string input) {
            SpaceBox_3D.BrailleServiceReference.ConvertTextToBrailleRequest inValue = new SpaceBox_3D.BrailleServiceReference.ConvertTextToBrailleRequest();
            inValue.Body = new SpaceBox_3D.BrailleServiceReference.ConvertTextToBrailleRequestBody();
            inValue.Body.input = input;
            SpaceBox_3D.BrailleServiceReference.ConvertTextToBrailleResponse retVal = ((SpaceBox_3D.BrailleServiceReference.BrailleServiceSoap)(this)).ConvertTextToBraille(inValue);
            return retVal.Body.ConvertTextToBrailleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SpaceBox_3D.BrailleServiceReference.ConvertTextToBrailleResponse> SpaceBox_3D.BrailleServiceReference.BrailleServiceSoap.ConvertTextToBrailleAsync(SpaceBox_3D.BrailleServiceReference.ConvertTextToBrailleRequest request) {
            return base.Channel.ConvertTextToBrailleAsync(request);
        }
        
        public System.Threading.Tasks.Task<SpaceBox_3D.BrailleServiceReference.ConvertTextToBrailleResponse> ConvertTextToBrailleAsync(string input) {
            SpaceBox_3D.BrailleServiceReference.ConvertTextToBrailleRequest inValue = new SpaceBox_3D.BrailleServiceReference.ConvertTextToBrailleRequest();
            inValue.Body = new SpaceBox_3D.BrailleServiceReference.ConvertTextToBrailleRequestBody();
            inValue.Body.input = input;
            return ((SpaceBox_3D.BrailleServiceReference.BrailleServiceSoap)(this)).ConvertTextToBrailleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SpaceBox_3D.BrailleServiceReference.GetDotsAmountResponse SpaceBox_3D.BrailleServiceReference.BrailleServiceSoap.GetDotsAmount(SpaceBox_3D.BrailleServiceReference.GetDotsAmountRequest request) {
            return base.Channel.GetDotsAmount(request);
        }
        
        public int GetDotsAmount(string input) {
            SpaceBox_3D.BrailleServiceReference.GetDotsAmountRequest inValue = new SpaceBox_3D.BrailleServiceReference.GetDotsAmountRequest();
            inValue.Body = new SpaceBox_3D.BrailleServiceReference.GetDotsAmountRequestBody();
            inValue.Body.input = input;
            SpaceBox_3D.BrailleServiceReference.GetDotsAmountResponse retVal = ((SpaceBox_3D.BrailleServiceReference.BrailleServiceSoap)(this)).GetDotsAmount(inValue);
            return retVal.Body.GetDotsAmountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SpaceBox_3D.BrailleServiceReference.GetDotsAmountResponse> SpaceBox_3D.BrailleServiceReference.BrailleServiceSoap.GetDotsAmountAsync(SpaceBox_3D.BrailleServiceReference.GetDotsAmountRequest request) {
            return base.Channel.GetDotsAmountAsync(request);
        }
        
        public System.Threading.Tasks.Task<SpaceBox_3D.BrailleServiceReference.GetDotsAmountResponse> GetDotsAmountAsync(string input) {
            SpaceBox_3D.BrailleServiceReference.GetDotsAmountRequest inValue = new SpaceBox_3D.BrailleServiceReference.GetDotsAmountRequest();
            inValue.Body = new SpaceBox_3D.BrailleServiceReference.GetDotsAmountRequestBody();
            inValue.Body.input = input;
            return ((SpaceBox_3D.BrailleServiceReference.BrailleServiceSoap)(this)).GetDotsAmountAsync(inValue);
        }
    }
}
