//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceBox_3D.BrailleServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BrailleServiceReference.BrailleServiceSoap")]
    public interface BrailleServiceSoap {
        
        // CODEGEN: Generating message contract since element name input from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TrasnlateToBraille", ReplyAction="*")]
        SpaceBox_3D.BrailleServiceReference.TrasnlateToBrailleResponse TrasnlateToBraille(SpaceBox_3D.BrailleServiceReference.TrasnlateToBrailleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TrasnlateToBraille", ReplyAction="*")]
        System.Threading.Tasks.Task<SpaceBox_3D.BrailleServiceReference.TrasnlateToBrailleResponse> TrasnlateToBrailleAsync(SpaceBox_3D.BrailleServiceReference.TrasnlateToBrailleRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TrasnlateToBrailleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TrasnlateToBraille", Namespace="http://tempuri.org/", Order=0)]
        public SpaceBox_3D.BrailleServiceReference.TrasnlateToBrailleRequestBody Body;
        
        public TrasnlateToBrailleRequest() {
        }
        
        public TrasnlateToBrailleRequest(SpaceBox_3D.BrailleServiceReference.TrasnlateToBrailleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TrasnlateToBrailleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public TrasnlateToBrailleRequestBody() {
        }
        
        public TrasnlateToBrailleRequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TrasnlateToBrailleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TrasnlateToBrailleResponse", Namespace="http://tempuri.org/", Order=0)]
        public SpaceBox_3D.BrailleServiceReference.TrasnlateToBrailleResponseBody Body;
        
        public TrasnlateToBrailleResponse() {
        }
        
        public TrasnlateToBrailleResponse(SpaceBox_3D.BrailleServiceReference.TrasnlateToBrailleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TrasnlateToBrailleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TrasnlateToBrailleResult;
        
        public TrasnlateToBrailleResponseBody() {
        }
        
        public TrasnlateToBrailleResponseBody(string TrasnlateToBrailleResult) {
            this.TrasnlateToBrailleResult = TrasnlateToBrailleResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BrailleServiceSoapChannel : SpaceBox_3D.BrailleServiceReference.BrailleServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BrailleServiceSoapClient : System.ServiceModel.ClientBase<SpaceBox_3D.BrailleServiceReference.BrailleServiceSoap>, SpaceBox_3D.BrailleServiceReference.BrailleServiceSoap {
        
        public BrailleServiceSoapClient() {
        }
        
        public BrailleServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BrailleServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BrailleServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BrailleServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SpaceBox_3D.BrailleServiceReference.TrasnlateToBrailleResponse SpaceBox_3D.BrailleServiceReference.BrailleServiceSoap.TrasnlateToBraille(SpaceBox_3D.BrailleServiceReference.TrasnlateToBrailleRequest request) {
            return base.Channel.TrasnlateToBraille(request);
        }
        
        public string TrasnlateToBraille(string input) {
            SpaceBox_3D.BrailleServiceReference.TrasnlateToBrailleRequest inValue = new SpaceBox_3D.BrailleServiceReference.TrasnlateToBrailleRequest();
            inValue.Body = new SpaceBox_3D.BrailleServiceReference.TrasnlateToBrailleRequestBody();
            inValue.Body.input = input;
            SpaceBox_3D.BrailleServiceReference.TrasnlateToBrailleResponse retVal = ((SpaceBox_3D.BrailleServiceReference.BrailleServiceSoap)(this)).TrasnlateToBraille(inValue);
            return retVal.Body.TrasnlateToBrailleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SpaceBox_3D.BrailleServiceReference.TrasnlateToBrailleResponse> SpaceBox_3D.BrailleServiceReference.BrailleServiceSoap.TrasnlateToBrailleAsync(SpaceBox_3D.BrailleServiceReference.TrasnlateToBrailleRequest request) {
            return base.Channel.TrasnlateToBrailleAsync(request);
        }
        
        public System.Threading.Tasks.Task<SpaceBox_3D.BrailleServiceReference.TrasnlateToBrailleResponse> TrasnlateToBrailleAsync(string input) {
            SpaceBox_3D.BrailleServiceReference.TrasnlateToBrailleRequest inValue = new SpaceBox_3D.BrailleServiceReference.TrasnlateToBrailleRequest();
            inValue.Body = new SpaceBox_3D.BrailleServiceReference.TrasnlateToBrailleRequestBody();
            inValue.Body.input = input;
            return ((SpaceBox_3D.BrailleServiceReference.BrailleServiceSoap)(this)).TrasnlateToBrailleAsync(inValue);
        }
    }
}
